Fixed some bugs and upped background resolution
Fixed the 2 most common errors that I encountered:
 - The "SoX error" (That's what it's called in JasonLovesDoggo's repo)
 - AttributeError: 'dict' object has no attribute 'title'

Fixed the ending being glitchy and freezing

Upped the resolution of the background cause it looked bad